import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head';
import Dashboard from '../components/Dashboard/Dashboard';

const index: NextPage = () => {

  return( <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Dashboard />
   </>);
};

export default index;
